#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    # 动态数据源文档 https://www.kancloud.cn/tracy5546/dynamic-datasource/content
#    dynamic:
#      # 性能分析插件(有性能损耗 不建议生产环境使用)
#      p6spy: true
#      # 设置默认的数据源或者数据源组,默认值即为 master
#      primary: master
#      # 严格模式 匹配不到数据源则报错
#      strict: true
#      datasource:
#        # 主库数据源
#        master:
#          driverClassName: com.mysql.cj.jdbc.Driver
#          # jdbc 所有参数配置参考 https://lionli.blog.csdn.net/article/details/122018562
#          # rewriteBatchedStatements=true 批处理优化 大幅提升批量插入更新删除性能(对数据库有性能损耗 使用批量操作应考虑性能问题)
#          url: jdbc:mysql://${S2_DB_HOST:192.168.0.115}:${S2_DB_PORT:3306}/${S2_DB_DATABASE:supersonic}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
#          username: ${S2_DB_USER:root}
#          password: ${S2_DB_PASSWORD:Yeacer@123456}
#        # 从库数据源
#        slave:
#          lazy: true
#          driverClassName: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://${S2_DB_HOST:192.168.0.115}:${S2_DB_PORT:3306}/poweropp_ee_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
#          username: ${S2_DB_USER:root}
#          password: ${S2_DB_PASSWORD:Yeacer@123456}


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${S2_DB_HOST:192.168.0.115}:${S2_DB_PORT:3306}/${S2_DB_DATABASE:supersonic}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: ${S2_DB_USER:root}
    password: ${S2_DB_PASSWORD:Yeacer@123456}
#  sql:
#    init:
#      continue-on-error: true
#      mode: always
#      username: ${S2_DB_USER:root}
#      password: ${S2_DB_PASSWORD:}
#      schema-locations: classpath:db/schema-mysql.sql,classpath:db/schema-mysql-demo.sql
#      data-locations: classpath:db/data-mysql.sql,classpath:db/data-mysql-demo.sql