spring:
 datasource:
   type: com.zaxxer.hikari.HikariDataSource
   dynamic:
     # 性能分析插件(有性能损耗 不建议生产环境使用)
     p6spy: false
     # 设置默认的数据源或者数据源组,默认值即为 master
     primary: master
     # 严格模式 匹配不到数据源则报错
     strict: true
     datasource:
       # 主库数据源
       master:
         type: ${spring.datasource.type}
         driver-class-name: com.mysql.cj.jdbc.Driver
         url: jdbc:mysql://${S2_DB_HOST:192.168.0.115}:${S2_DB_PORT:3306}/${S2_DB_DATABASE:supersonic}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
         username: ${S2_DB_USER:root}
         password: ${S2_DB_PASSWORD:Yeacer@123456}
       # 从库数据源
       slave:
         lazy: true
         type: ${spring.datasource.type}
         driver-class-name: com.mysql.cj.jdbc.Driver
         url: jdbc:mysql://${S2_DB_HOST:192.168.0.115}:${S2_DB_PORT:3306}/poweropp_ee_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
         username: ${S2_DB_USER:root}
         password: ${S2_DB_PASSWORD:Yeacer@123456}
     hikari:
       # 最大连接池数量
       maxPoolSize: 20
       # 最小空闲线程数量
       minIdle: 10
       # 配置获取连接等待超时的时间
       connectionTimeout: 30000
       # 校验超时时间
       validationTimeout: 5000
       # 空闲连接存活最大时间，默认10分钟
       idleTimeout: 600000
       # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
       maxLifetime: 1800000
       # 连接测试query（配置检测连接是否有效）
       connectionTestQuery: SELECT 1
       # 多久检查一次连接的活性
       keepaliveTime: 30000


# spring:
#   datasource:
#     type: com.zaxxer.hikari.HikariDataSource
#     hikari:
#       username: ${S2_DB_USER:root}
#       password: ${S2_DB_PASSWORD:Yeacer@123456}
#       jdbc-url: jdbc:mysql://${S2_DB_HOST:192.168.0.115}:${S2_DB_PORT:3306}/${S2_DB_DATABASE:supersonic}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
#   sql:
#     init:
#       continue-on-error: true
#       mode: always
#       username: ${S2_DB_USER:root}
#       password: ${S2_DB_PASSWORD:}
#       schema-locations: classpath:db/schema-mysql.sql,classpath:db/schema-mysql-demo.sql
#       data-locations: classpath:db/data-mysql.sql,classpath:db/data-mysql-demo.sql