package com.tencent.supersonic.headless.api.pojo;

import lombok.Data;

import java.io.Serializable;

@Data
public class DaxInfo implements Serializable {
    private static final long serialVersionUID = 1L;

    // S2DAX generated by semantic parsers
    private String parsedS2DAX;

    // S2DAX corrected by semantic correctors
    private String correctedS2DAX;

    // DAX to be executed finally
    private String queryDAX;
}
